# @package _global_
defaults:
  - model: token

seed: 7
num_workers: 8
log_offline: false

# data keys
raw_data_folder: /home/niexu/dataset
# data_folder: /home/public/rmt/niexu/projects/python/noise_reduce/data/
data_folder: data/
# geo_folder: /home/public/rmt/niexu/projects/python/noise_reduce/train_data_geo/
# geo_folder: /home/public/rmt/niexu/projects/python/noise_reduce/data/geo/
res_folder: res
noise_set: all
noise_rate: 0
sampleType: downsample
save_every_epoch: 1
val_every_epoch: 1
log_every_epoch: 10
progress_bar_refresh_rate: 1